name: Hit Tweet API

on:
  schedule:
    - cron: '*/29 * * * *'  # Runs every 29 minutes to get close to 50 tweets per day

jobs:

  hit-api:
    runs-on: ubuntu-latest

    steps:
    - name: Hit API
      run: |
        curl -X POST botx-43zlfww7p-ombhojanes-projects.vercel.app/api/tweet
